#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Provisions the Gentoo system from inside its chroot. Invoked by builder.sh;
# safe to rerun.
set -eo pipefail
source /etc/profile
set -u
setup=/root/vm-setup

packages=(
    # Kernel and boot
    sys-kernel/gentoo-kernel-bin sys-boot/grub sys-fs/dosfstools
    # Session, login, and basic administration
    sys-auth/elogind sys-apps/dbus app-admin/sudo net-misc/dhcpcd
    dev-vcs/git net-misc/rsync app-misc/tmux dev-debug/gdb sys-apps/pciutils
    # shaoDe build dependencies (docs/gentoo.md)
    gui-libs/wlroots:0.20 dev-lang/lua:5.4 dev-libs/wayland
    dev-libs/wayland-protocols dev-util/wayland-scanner x11-libs/libxkbcommon
    dev-build/cmake dev-build/ninja virtual/pkgconfig
    dev-qt/qtbase:6 dev-qt/qtdeclarative:6 dev-qt/qtwayland:6
    kde-plasma/layer-shell-qt:6 dev-libs/glib:2
    x11-base/xwayland x11-libs/libxcb
    # Clients for interactive testing
    gui-apps/foot x11-terms/kitty x11-terms/xterm
    gui-apps/swaylock gui-apps/swayidle app-misc/wayland-utils x11-apps/mesa-progs
    media-fonts/dejavu x11-themes/adwaita-icon-theme x11-misc/xdg-utils
)

cat >/etc/portage/make.conf <<EOF
# Generated by shaoDe tools/gentoo-vm/chroot.sh
COMMON_FLAGS="-O2 -pipe -march=x86-64-v3"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"
MAKEOPTS="-j$JOBS -l$JOBS"
EMERGE_DEFAULT_OPTS="--jobs=4 --load-average=$JOBS --quiet-build=y"
FEATURES="getbinpkg binpkg-request-signature"
ACCEPT_LICENSE="*"
USE="elogind -systemd wayland X dbus"
VIDEO_CARDS="virgl"
INPUT_DEVICES="libinput"
GRUB_PLATFORMS="efi-64"
LC_MESSAGES=C.UTF-8
EOF

cat >/etc/portage/binrepos.conf/gentoobinhost.conf <<'EOF'
[gentoo]
priority = 1
sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64-v3
location = /var/cache/binhost/gentoo
verify-signature = true
EOF

mkdir -p /etc/portage/package.use
cat >/etc/portage/package.use/shaode <<'EOF'
gui-libs/wlroots X drm libinput session
sys-kernel/installkernel dracut grub
EOF

[[ -d /var/db/repos/gentoo/profiles ]] || emerge-webrsync --quiet
eselect profile set default/linux/amd64/23.0/desktop
getuto

emerge --update --deep --newuse --noreplace \
    --autounmask=y --autounmask-continue=y \
    @world "${packages[@]}"

# Base system configuration
ln -sf "/usr/share/zoneinfo/$VM_TIMEZONE" /etc/localtime
echo "$VM_TIMEZONE" >/etc/timezone
grep -q '^en_US.UTF-8' /etc/locale.gen || echo 'en_US.UTF-8 UTF-8' >>/etc/locale.gen
locale-gen --quiet
eselect locale set en_US.utf8
echo 'hostname="shaode-gentoo"' >/etc/conf.d/hostname

# Boot: EFI system partition, GRUB (removable path, no NVRAM), dracut
blkid -p "$ESP_DEV" | grep -q vfat || mkfs.vfat -F 32 -n ESP "$ESP_DEV"
mkdir -p /efi
mountpoint -q /efi || mount "$ESP_DEV" /efi
cat >/etc/fstab <<EOF
UUID=$(blkid -s UUID -o value "$ROOT_DEV")  /     ext4  defaults,noatime  0 1
UUID=$(blkid -s UUID -o value "$ESP_DEV")  /efi  vfat  umask=0077        0 2
EOF

mkdir -p /etc/dracut.conf.d
cat >/etc/dracut.conf.d/vm.conf <<'EOF'
hostonly="no"
add_drivers+=" virtio_blk virtio_pci virtio_gpu "
EOF
sed -i \
    -e 's/^#\?GRUB_TIMEOUT=.*/GRUB_TIMEOUT=2/' \
    -e 's/^#\?GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 console=tty0"/' \
    /etc/default/grub
grub-install --target=x86_64-efi --efi-directory=/efi --removable --no-nvram
grub-mkconfig -o /boot/grub/grub.cfg
umount /efi

# Services
rc-update add elogind boot
rc-update add dbus default
rc-update add dhcpcd default
rc-update add sshd default
ln -sf agetty /etc/init.d/agetty.ttyS0
rc-update add agetty.ttyS0 default

# Users: password "shaode" for root and the user; key-based SSH. The hash
# is set directly because PAM's passwdqc rejects such a weak password.
hash=$(openssl passwd -6 shaode)
echo "root:$hash" | chpasswd -e
id "$VM_USER" &>/dev/null ||
    useradd -m -G users,wheel,audio,video,input -s /bin/bash "$VM_USER"
echo "$VM_USER:$hash" | chpasswd -e
mkdir -p /etc/sudoers.d
echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >/etc/sudoers.d/wheel
chmod 0440 /etc/sudoers.d/wheel
install -d -m 0700 -o "$VM_USER" -g "$VM_USER" "/home/$VM_USER/.ssh"
install -m 0600 -o "$VM_USER" -g "$VM_USER" "$setup/authorized_keys" \
    "/home/$VM_USER/.ssh/authorized_keys"

rm -f /etc/resolv.conf
echo "Provisioning complete"
